### ISSUE TITLE
Difficulté de transcription - Pensées sur la religion, par Blaise PASCAL.

### ISSUE THREAD

**Issue by alix-tz** [HTR-United/CREMMA-MSS-17#10]
Dans ` 6_d7979_default.jpg` je pense qu'il vaudrait mieux transcrire "FEV". Un avis ?

![image](https://user-images.githubusercontent.com/33317799/178011031-d6907629-81b4-40ba-997c-7689ee585eaf.png)

**Comment by alix-tz** [comment]
Même problème ici : 
![image](https://user-images.githubusercontent.com/33317799/178011355-eb88351e-36db-478c-b17f-fb46116d0c35.png)


C'est vrai qu'on est bien censés lire "Feu" et "Dieu"...

**Comment by alix-tz** [comment]
cf https://github.com/HTR-United/CREMMA-MSS-17/issues/1#issuecomment-1179038907

![image](https://user-images.githubusercontent.com/33317799/178011662-9efacc58-5f88-4f87-9eb7-54c201e4f88c.png)

Qu'est-ce qui vaut mieux, ` eternellem.^t`  ou ` eternellem^t.`  ? Le point n'est là que pour signaler l'abréviation et certains éditeurs considèrent qu'il n'est pas à transcrire. Ici ce qui m'interpelle c'est qu'il est franchement écrit après le "t"

**Comment by alix-tz** [comment]
@PonteIneptique  @jnorindr

**Comment by snorindr** [comment]
Je m'en remets à vous pour ce qui est de "FEV" et "DIEV", je ne savais en effet pas ce qui était préférable !
Pour `eternellem^t.`, en le comparant avec d'autres abréviations, le point est en effet bien après le "t", j'ai donc changé `eternellem.^t` en `eternellem^t.` dans la transcription.

**Comment by alix-tz** [comment]
Vu ce qu'on a décidé pour https://github.com/HTR-United/cremma-wikipedia/issues/10, en privilégiant la réduction des confusions entre les lettres plutôt que ce qu'on devrait lire, je pense qu'on peut opter pour "FEV" et "DIEV"

**Comment by snorindr** [comment]
C'est modifié, merci.
