### ISSUE TITLE
Montfaucon : synchro avec le projet "Cremma" sur eScriptorium

### ISSUE THREAD

**Issue by alix-tz** [HTR-United/CREMMA-MSS-17#4]
Bonjour @margauxfre,

Sauf erreur de ma part, je ne trouve pas votre document "Correspondance de Dom Bernard de Montfaucon" dans le [projet "Cremma"](https://escriptorium.inria.fr/project/cremma/documents/) sur eScriptorium, pouvez-vous l'y ajouter ? A minima, pouvez-vous ajouter l'adresse vers le document dans le tableau de suivi des transcriptions ? Il y a une colonne pour cela nommée "URL eScriptorium" (colonne S).

Merci d'avance ! 😃

**Comment by margauxfre** [comment]
Bonjour Alix,

En effet, j'avais travaillé en dehors du projet et ai ensuite oublié d'ajouter le document. C'est chose faite maintenant ! Toutes mes excuses pour le contretemps.

Merci !

**Comment by alix-tz** [comment]
Super, merci beaucoup !
