### ISSUE TITLE
Dépêches : synchro avec le projet "cremma" sur eScriptorium

### ISSUE THREAD

**Issue by alix-tz** [HTR-United/CREMMA-MSS-17#5]
Bonjour @baudbaudy ,

Sauf erreur de ma part, je ne vois pas le document correspondant à "Dépêches originales adressées à la Cour par divers ambassadeurs et agents français en Angleterre" dans le [projet "Cremma"](https://escriptorium.inria.fr/project/cremma/documents/) sur eScriptorium. Si vous avez déjà commencé à travailler dessus, pouvez-vous indiquer dans la colonne S ("URL eScriptorium) du tableau de suivi des transcriptions le lien vers le document eScriptorium correspondant, voire l'ajouter au bon projet ?

**Comment by alix-tz** [comment]
C'est bon, je vois que vous avez rectifié. Merci beaucoup !

**Comment by baudbaudy** [comment]
Bonsoir à vous,

Alors j'ai un problème avec le document  "Dépêches originales adressées à
la Cour par divers ambassadeurs et agents français en Angleterre". Si vous
ne trouviez pas les jours précédents le lien des images vers escriptorium
c'est tout simplement que, pour une raison que j'ignore, le site ne voulait
pas télécharger les images. J'ai de nouveau essayer aujourd'hui, le site a
accepté de les télécharger cette fois. Cependant je rencontre maintenant un
autre problème, les images sont de mauvaise qualité alors que pourtant sur
la visionneuse IIIF de gallica il est possible de les avoir avec une très
bonne résolution (si vous vous rappelez j'avais eu le même souci avec les
papiers de Georges Sand. J'ai réussi à corriger le problème avec George
Sand mais là je n'y arrive pas).

Le dim. 20 mars 2022 à 23:13, Alix Chagué ***@***.***> a
écrit :
